version: 2
jobs:
  build:
    docker:
      - image: node:13

    working_directory: ~/Music-shop/server

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: node:13
    steps:
      - checkout
      - run:
          name: Deploy to server
          command: |
            ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "~/build_server.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          # Only runs for Production branch
          filters:
            branches:
              only:
                - Production
          requires:
            - build
